#!/bin/bash

dpkg-reconfigure tzdata
apt-get update

sudo mount /dev/mmcblk0p1 /mnt
echo disable_overscan=0 >> /mnt/config.txt
echo hdmi_group=1 >> /mnt/config.txt
echo hdmi_hot_plug=1 >> /mnt/config.txt
echo hdmi_mode=33 >> /mnt/config.txt
echo disable_splash=1 >> /mnt/config.txt
echo boot_delay=0 >> /mnt/config.txt
echo elevator=deadline quiet datadev=mmcblk0p2 bootmenutimeout=0 logo.nologo console=tty3 splash loglevel=3 vt.global_cursor_default=0 plymouth.ignore-serial-consoles > /mnt/cmdline.txt
echo "0 3  * * * root  reboot" >> /etc/crontab
echo "0 5  * * * root  /home/pi/timer/res/time-update.sh" >> /etc/crontab
echo "0 10  * * * root  /home/pi/timer/res/time-update.sh" >> /etc/crontab
echo "0 15  * * * root  /home/pi/timer/res/time-update.sh" >> /etc/crontab
echo "0 20  * * * root  /home/pi/timer/res/time-update.sh" >> /etc/crontab

cd /home/pi
apt-get install -y qt5-qmake qt5-default libqt5svg5-dev git unclutter

git clone https://github.com/petrix/oscpack.git
git clone https://github.com/petrix/timer.git
cp /usr/share/plymouth/themes/pix/splash.png /usr/share/plymouth/themes/pix/splash_backup.png
cp /home/pi/timer/res/casparcg_boot.png /usr/share/plymouth/themes/pix/splash.png
cp /home/pi/timer/res/autostart.conf /home/pi/.config/lxsession/LXDE-pi/autostart
chmod a+x /home/pi/timer/run.sh
chmod a+x /home/pi/timer/res/time-update.sh

cd /home/pi/oscpack

make && make install

sudo /sbin/ldconfig -v

cd /home/pi/timer



qmake && make

cp timer timer.sh

reboot

//
